apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadqssn7535-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadqssn7535-tenant-component
    app.kubernetes.io/part-of: loadqssn7535-tenant-app
  name: loadqssn7535-tenant-component
  namespace: loadqssn7535-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadqssn7535-tenant-component
    weight: null
status: {}
